language: node_js

node_js:
  - 9

cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules

branches:
  only:
  - master
  - develop
  
script:
  - echo $TRAVIS_BRANCH
  - npm run build
  - ls -R $TRAVIS_BUILD_DIR/build

deploy:
  - provider: firebase
    token:
      secure: "CcsRsHT+B9CmsMPkVjjHv4+FCSUqp7G013dl79eJZrlqt7kURFBzypwd60DKMdDU7dx5r21LjF0ooo6+E7CbANAylLVcrL+MMv3PvQSe2L8e3osH/Y3gUz+18QYYJCxasExTRrIUbNs1Hhbd4MizyORwhl30W6tIAm5QeYRS4kIWHA7zB5uTco+L9TtKTM5S41dikmyc1DEOFArgOpLXt/ek4Jk13KdU7bPq1K5YPEL5Hg5ugoz/zelgLVPliFp/8WfnrVJ2bRZx4oBcwTQa/CKqqXtuS3fRvh4fx1vlw9TuQx73medt0pZn4TTVn7xIlm2GtQIAlATPvku+z2ZvIAMHqDKCJlS+hzBqVxXVyv5Wtl0APnKa+b6Fp78w2UbysAzjanhBnXLR0sfCcWi4m6dpo23ljxEejRbEWJgU8PMPmMk7ptEahfEfgA3TJjAzZQ+BaPdEDfvnuzUbbfOZbmxLiLQO8Y/oZPS+T3Z0NMZvWCRR4Amhci15M/c0+vF0aXj32VWfSY2rYlqik56AQGG8qHFRtBbcmvYdHAKY6vkXPDi2U71JYqp478aOYTm4k48OVZn3ehjxzycI7EHxl01E9a7aL3AVdIsvl5TS5+qof0sTym3Nkzm6sS5i2tkZ9ENTCTGe8+8JaawlAvh2TDtPoABrMjQMpWtJgNc3zhk="
    project: "production"
    message: "deploying to production"
    on:
      branch: master
    skip_cleanup: true
  - provider: firebase
    token:
      secure: "KjJPzjslgoArgsgkbjJY7rSwu9/xeoMFcCh/+e/6jRbradmjJRZ3ct7CME6xN6l5z7C1Xqud886HwPUxovsGjWKBXXdiB2Khr2hslmrG2ThxVZ2yX3JdptmWk59HT4q0Js6GYH2NBsPozQNWC5MqkjjH0wAGNE2iKVA6lLUzpvjZhVxC6IXtd4CpwV1BAYz1y6d4K3gsFEem+OhCSFhW1ajr024UqAV+3fyE4sfGA088a6veGmTd8qihNPG0PsEUwDM0Pm8oN/Ms9Zd5Q4zou3mLRtoANm0ukxggf0IgqAZYIAELl4ziUuq+P7qmoTgkgpaeS5Co229+/n9JckU5gQFjynFMNB240vM4RgNhprCc4DcUlqh6IplXw2eFG3JmMvTNOV4Vn0GTlLNnL1f5ZrYLmGrCHkj5EJo4Q/6B7NDtKxcjZJG1f8GlHlQHyHmVb/co0YLOoIxIGq+9rlh1a+j/uIK1C49/KmPXR8Pzd1YSQy281604UUmPtxowDS8hWNWQJnxg6LB+CK1je1SXJl7UmosmosEbAkuZ6LDIhi3tTeujng6vOqk8vLii2Q7fOlMd3UhliNJK1b0nymkBPswM+7U1Q3Jx1whqNFH/+b+1IVIwmpKfj7RUfg6llppdt2cohepi6N9xBw8MUVU3+uLxoxWOHDLIj55mvdMrhOc="
    project: "develop"
    message: "deploying to staging"
    on:
      branch: develop
    skip_cleanup: true
