language: node_js

node_js:
  - 7

cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules

script:
  - ls $TRAVIS_BUILD_DIR
  - npm run build
  - ls $TRAVIS_BUILD_DIR

deploy:
  provider: firebase
  token:
    secure: "CcsRsHT+B9CmsMPkVjjHv4+FCSUqp7G013dl79eJZrlqt7kURFBzypwd60DKMdDU7dx5r21LjF0ooo6+E7CbANAylLVcrL+MMv3PvQSe2L8e3osH/Y3gUz+18QYYJCxasExTRrIUbNs1Hhbd4MizyORwhl30W6tIAm5QeYRS4kIWHA7zB5uTco+L9TtKTM5S41dikmyc1DEOFArgOpLXt/ek4Jk13KdU7bPq1K5YPEL5Hg5ugoz/zelgLVPliFp/8WfnrVJ2bRZx4oBcwTQa/CKqqXtuS3fRvh4fx1vlw9TuQx73medt0pZn4TTVn7xIlm2GtQIAlATPvku+z2ZvIAMHqDKCJlS+hzBqVxXVyv5Wtl0APnKa+b6Fp78w2UbysAzjanhBnXLR0sfCcWi4m6dpo23ljxEejRbEWJgU8PMPmMk7ptEahfEfgA3TJjAzZQ+BaPdEDfvnuzUbbfOZbmxLiLQO8Y/oZPS+T3Z0NMZvWCRR4Amhci15M/c0+vF0aXj32VWfSY2rYlqik56AQGG8qHFRtBbcmvYdHAKY6vkXPDi2U71JYqp478aOYTm4k48OVZn3ehjxzycI7EHxl01E9a7aL3AVdIsvl5TS5+qof0sTym3Nkzm6sS5i2tkZ9ENTCTGe8+8JaawlAvh2TDtPoABrMjQMpWtJgNc3zhk="
  project: "production"
  message: "deploying to production"